#!/usr/bin/env python
# -*- coding:utf-8 -*-

from .keywords import (
  WafLoginKeywords,
  WafMainKeywords,
  WafMainSecurityKeywords,
  WafMainSituationKeywords,
  WafMainWebflowKeywords,
  WafMainNetflowKeywords,
  WafMainNetworkKeywords,
  WafMainHistoryKeywords,
  WafLogsAlarmsKeywords,
  WafLogsMlKeywords,
  WafLogsAnticcKeywords,
  WafLogsNetworkKeywords,
  WafLogsIpPrestigeKeywords,
  WafLogsStatsKeywords,
  WafLogsAnalyzeKeywords,
  WafLogsActionsKeywords,
  WafLogsSystemKeywords,
  WafLogsUpdateKeywords,
  WafReportCustomListKeywords,
  WafReportComboListKeywords,
  WafReportTimedListKeywords,
  WafReportPciDssKeywords,
  WafRulesGroupMainKeywords,
  WafRulesCustomMainKeywords,
  WafRulesMlKeywords,
  WafRulesVirtualPatchKeywords,
  WafRulesAnticcKeywords,
  WafRulesAntiStealingLinkKeywords,
  WafRulesIpPrestigeKeywords,
  WafRulesAntiddosKeywords,
  WafRulesUpdateKeywords,
  WafConfigGlobalKeywords,
  WafConfigWebappListKeywords,
  WafConfigWebappSslKeywords,
  WafConfigFirewallKeywords,
  WafConfigLogKeywords,
  WafConfigNoticeKeywords,
  WafConfigHaKeywords,
  WafConfigMonitorKeywords,
  WafConfigNetworkKeywords,
  WafConfigWebproxyKeywords,
  WafConfigAlmodifyKeywords,
  WafConfigManagementKeywords,
  WafSystemMaintenanceKeywords,
  WafSystemSettingsKeywords,
  WafSystemUserKeywords,
  WafSystemUserEditKeywords,
  WafSystemLicenseKeywords,
  WafSystemDataKeywords,
  WafSystemUpdateKeywords,
  WafSystemSettingsApplyKeywords,
  WafSystemreReservedKeywords
)

__version__ = "0.0.1"

class WafWebLibrary(
  WafLoginKeywords,
  WafMainKeywords,
  WafMainSecurityKeywords,
  WafMainSituationKeywords,
  WafMainWebflowKeywords,
  WafMainNetflowKeywords,
  WafMainNetworkKeywords,
  WafMainHistoryKeywords,
  WafLogsAlarmsKeywords,
  WafLogsMlKeywords,
  WafLogsAnticcKeywords,
  WafLogsNetworkKeywords,
  WafLogsIpPrestigeKeywords,
  WafLogsStatsKeywords,
  WafLogsAnalyzeKeywords,
  WafLogsActionsKeywords,
  WafLogsSystemKeywords,
  WafLogsUpdateKeywords,
  WafReportCustomListKeywords,
  WafReportComboListKeywords,
  WafReportTimedListKeywords,
  WafReportPciDssKeywords,
  WafRulesGroupMainKeywords,
  WafRulesCustomMainKeywords,
  WafRulesMlKeywords,
  WafRulesVirtualPatchKeywords,
  WafRulesAnticcKeywords,
  WafRulesAntiStealingLinkKeywords,
  WafRulesIpPrestigeKeywords,
  WafRulesAntiddosKeywords,
  WafRulesUpdateKeywords,
  WafConfigGlobalKeywords,
  WafConfigWebappListKeywords,
  WafConfigWebappSslKeywords,
  WafConfigFirewallKeywords,
  WafConfigLogKeywords,
  WafConfigNoticeKeywords,
  WafConfigHaKeywords,
  WafConfigMonitorKeywords,
  WafConfigNetworkKeywords,
  WafConfigWebproxyKeywords,
  WafConfigAlmodifyKeywords,
  WafConfigManagementKeywords,
  WafSystemMaintenanceKeywords,
  WafSystemSettingsKeywords,
  WafSystemUserKeywords,
  WafSystemUserEditKeywords,
  WafSystemLicenseKeywords,
  WafSystemDataKeywords,
  WafSystemUpdateKeywords,
  WafSystemSettingsApplyKeywords,
  WafSystemreReservedKeywords
):
  ROBOT_LIBRARY_SCOPE = "GLOBAL"
  ROBOT_LIBRARY_VERSION = __version__

    